version: '3.8'

services:
  app-backend:
    image: directus/directus:11.5.1
    container_name: app-backend
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@app.megamail.ir"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: app-db
      DB_PORT: 5432
      DB_DATABASE: megamail
      DB_USER: megamail_user
      DB_PASSWORD: megamail_pass
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://megamail.ir"
    depends_on:
      - app-db

  app-db:
    image: postgres:15
    container_name: app-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - megamail_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: megamail
      POSTGRES_USER: megamail_user
      POSTGRES_PASSWORD: megamail_pass

  megamail-frontend:
    build: ./megamail
    container_name: megamail-frontend
    ports:
      - 3000:3000
    environment:
      VITE_API_BASE_URL: https://app.megamail.ir

volumes:
  megamail_pgdata:
